version: 2
jobs:
  test:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      K8S_VERSION: v1.15.2
      KUBECONFIG: /home/circleci/.kube/config
      MINIKUBE_VERSION: v1.3.1
      MINIKUBE_HOME: /home/circleci
    steps:
      - checkout
      - run:
          name: setup kubectl
          command: |
            curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/${K8S_VERSION}/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
            mkdir -p ${HOME}/.kube
            touch ${HOME}/.kube/config
      - run:
          name: setup minikube
          command: |
            curl -Lo minikube https://github.com/kubernetes/minikube/releases/download/${MINIKUBE_VERSION}/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
      - run:
          name: setup helm
          command: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get | bash
      - run:
          name: start minikube
          command: |
            sudo minikube start --vm-driver=none --cpus 2 --memory 4096 --kubernetes-version=${K8S_VERSION} &> $HOME/minikube.log 2>&1 < /dev/null
      - run:
          name: fix permission
          command: |
            sudo chown circleci:circleci -R /home/circleci/.minikube
            sudo mkdir -p /etc/kubernetes 
            sudo chown circleci:circleci -R /etc/kubernetes
      - run:
          name: debug node
          command: |
            kubectl describe node
      - run:
          name: wait for minikube
          command: |
            JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}';
            until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do
              sleep 1;
            done
      - run:
          name: Test the bug
          command: |
            ./script.sh

workflows:
  version: 2
  build:
    jobs:
      - test
